[package]
authors = ["Laurentiu Nicola <lnicola@dend.ro>"]
name = "rusty-share"
version = "0.1.0"

[dependencies]
bytes = "0.4.5"
bytesize = "0.1.3"
chrono = "0.4.0"
chrono-humanize = "0.0.10"
failure = "0.1.1"
futures = "0.1.17"
futures-await = "0.1.0"
futures-cpupool = "0.1.7"
horrorshow = "0.6.2"
hyper = "0.11.9"
log = "0.3.8"
pretty_env_logger = "0.1.1"
rayon = "0.9.0"
structopt = "0.1.6"
structopt-derive = "0.1.6"
tar = "0.4.14"
tokio-core = "0.1.11"
url = "1.6.0"
walkdir = "2.0.1"

[dependencies.futures-fs]
git = "https://github.com/seanmonstar/futures-fs"
