[package]
authors = ["Laurentiu Nicola <lnicola@dend.ro>"]
name = "rusty-share"
version = "0.1.0"

[dependencies]
bytes = "0.4"
bytesize = "1.0"
clap-port-flag = "0.3"
chrono = "0.4"
chrono-humanize = "0.0.11"
cookie = "0.11"
failure = "0.1"
futures-await = "0.1"
horrorshow = "0.6"
hex = "0.3"
http = "0.1"
http-serve = "0.1"
hyper = "0.12"
libpasta = "0.1.0-rc2"
log = "0.4"
mime-sniffer = "0.1"
pretty_env_logger = "0.2"
rand = "0.5"
rayon = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_urlencoded = "0.5"
structopt = "0.2"
tar = "0.4"
time = "0.1"
tokio = "0.1"
tokio-threadpool = "0.1"
url = "1.7"
walkdir = "2.2"

[dependencies.diesel]
default-features = false
features = ["chrono", "r2d2", "sqlite"]
version = "1.3"

[profile.release]
codegen-units = 1
lto = true
