[package]
authors = ["Laurentiu Nicola <lnicola@dend.ro>"]
name = "rusty-share"
version = "0.1.0"

[dependencies]
bytes = "0.4"
bytesize = "0.2"
chrono = "0.4"
chrono-humanize = "0.0.11"
failure = "0.1"
futures = "0.1"
futures-cpupool = "0.1"
horrorshow = "0.6"
http = "0.1"
http-serve = { git = "https://github.com/scottlamb/http-serve/" }
hyper = "0.12"
log = "0.4"
mime-sniffer = "0.1.2"
pretty_env_logger = "0.2"
rayon = "1"
structopt = "0.2"
tar = "0.4"
tokio = "0.1.5"
url = "1"
walkdir = "2"
