[package]
authors = ["Laurentiu Nicola <lnicola@dend.ro>"]
name = "rusty-share"
version = "0.1.0"

[dependencies]
bytes = "0.4"
bytesize = "0.1"
chrono = "0.4"
chrono-humanize = "0.0.11"
failure = "0.1"
futures = "0.1"
futures-await = "0.1"
futures-cpupool = "0.1"
horrorshow = "0.6"
http-serve = { git = "https://github.com/lnicola/http-serve/", branch = "fs-block-size" }
hyper = "0.11"
log = "0.4"
pretty_env_logger = "0.2"
rayon = "1.0"
structopt = "0.2"
tar = "0.4"
tokio-core = "0.1"
url = "1.6"
walkdir = "2.0"
mime-sniffer = "0.1.2"
