[package]
authors = ["Laurentiu Nicola <lnicola@dend.ro>"]
name = "rusty-share"
version = "0.1.0"

[dependencies]
bytes = "0.4.5"
bytesize = "0.1.3"
chrono = "0.4.0"
chrono-humanize = "0.0.10"
futures = "0.1.17"
futures-cpupool = "0.1.7"
futures-fs = "0.0.3"
hyper = "0.11.6"
pretty_env_logger = "0.1.1"
url = "1.6.0"
walkdir = "2.0.1"
