[package]
authors = ["Laurentiu Nicola <lnicola@dend.ro>"]
name = "rusty-share"
version = "0.1.0"

[dependencies]
bytes = "0.4"
bytesize = "0.1"
chrono = "0.4"
chrono-humanize = "0.0.10"
failure = "0.1"
futures = "0.1"
futures-cpupool = "0.1"
futures-fs = "0.0.3"
horrorshow = "0.6"
log = "0.3"
pretty_env_logger = "0.1"
rayon = "0.9"
structopt = "0.1"
structopt-derive = "0.1"
tar = "0.4"
tokio-core = "0.1"
url = "1.6"
walkdir = "2.0"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
