[package]
authors = ["Laurentiu Nicola <lnicola@dend.ro>"]
name = "rusty-share"
version = "0.1.0"

[dependencies]
bytes = "0.4.5"
bytesize = "0.1.3"
chrono = "0.4.0"
chrono-humanize = "0.0.10"
futures = "0.1.17"
futures-cpupool = "0.1.7"
futures-fs = "0.0.3"
horrorshow = "0.6.2"
pretty_env_logger = "0.1.1"
rayon = "0.9.0"
structopt = "0.1.5"
structopt-derive = "0.1.5"
tar = "0.4.13"
tokio-core = "0.1.10"
url = "1.6.0"
walkdir = "2.0.1"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
