[package]
authors = ["Laurentiu Nicola <lnicola@dend.ro>"]
name = "rusty-share"
version = "0.1.0"
edition = "2018"

[dependencies]
bytes = "0.4"
bytesize = "1.0"
chrono = "0.4"
chrono-humanize = "0.0.11"
cookie = "0.11"
diesel = { version = "1.3", default-features = false, features = ["chrono", "r2d2", "sqlite"] }
futures = "0.1"
hex = "0.3"
horrorshow = "0.6"
http = "0.1"
http-serve = "0.1"
hyper = "0.12"
log = "0.4"
mime_guess = "1.8"
pretty_env_logger = "0.2"
rand = "0.5"
rayon = "1.0"
scrypt = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_urlencoded = "0.5"
structopt = "0.2"
tar = "0.4"
time = "0.1"
tokio = "0.1"
tokio-threadpool = "0.1"
tower-web = { version = "0.3", default-features = false }
url = "1.7"
walkdir = "2.2"

[profile.release]
codegen-units = 1
lto = true
